'use strict';
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const names = ['core', 'config', 'domain', 'api', 'storage', 'engine', 'session', 'ui', 'main'];
const metadata = `// ==UserScript==
// @name         华科通用选课助手 · 课程与教师精确匹配
// @namespace    local.hust.chooseclass.generic
// @version      2.0.0
// @description  输入课程和教师，先只读检查再自动选课；不退课、不盲目重试，保留跨标签锁与待确认日志。
// @match        https://wsxk.hust.edu.cn/zyxxk/*
// @run-at       document-idle
// @grant        none
// @noframes
// ==/UserScript==`;
const modules = names.map(name => {
    const source = fs.readFileSync(path.join(root, 'src', `${name}.js`), 'utf8');
    return `${JSON.stringify('./' + name)}: function(module, exports, require) {\n${source}\n}`;
}).join(',\n\n');
const bundle = `${metadata}\n\n// Generated by scripts/build.cjs; edit src/*.js, then rebuild. No runtime dependency.\n(function () {\n'use strict';\nconst factories = {\n${modules}\n};\nconst cache = Object.create(null);\nfunction load(name) {\n    if (!factories[name]) throw new Error('Unknown module: ' + name);\n    if (!cache[name]) { const module = { exports: {} }; cache[name] = module; factories[name](module, module.exports, load); }\n    return cache[name].exports;\n}\nload('./main').boot(window, document);\n})();\n`;
fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
fs.writeFileSync(path.join(root, 'dist', 'hust-course-picker.user.js'), bundle);
console.log(`Built dist/hust-course-picker.user.js (${Buffer.byteLength(bundle)} bytes)`);
